version: "3.3"
services:
    octopus-bot:
      container_name: bot
      image: bot.jar:latest
      restart: on-failure
      ports:
        - "9944:9944"
      stdin_open: true
      tty: true
      networks:
        - nginx-net
      environment:
        - LANG=C.UTF-8
    octopus-rest:
      image: foodrest.jar:latest
      restart: on-failure
      container_name: rest
      environment:
        - "spring.data.mongodb.uri=mongodb://root:test@food-mongo:27055/octopus?authSource=admin&authMechanism=SCRAM-SHA-1"
      ports:
        - "9098:9098"
      stdin_open: true
      tty: true
      depends_on:
        - food-mongo
      networks:
        - nginx-net

networks:
  nginx-net:
    external: true