version: "3.3"
services:
    food-rest:
      image: foodrest:latest
      restart: on-failure
      environment:
        - "spring.data.mongodb.uri=mongodb://root:test@food-mongo:27055/test?authSource=admin&authMechanism=SCRAM-SHA-1"
      ports:
        - "9097:9097"
      stdin_open: true
      tty: true
      depends_on:
        - food-mongo
    food-mongo:
      image: mongo:4.2.0
      ports:
        - "27055:27055"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=test
        - MONGO_INITDB_DATABASE=test
      volumes:
        - mongodb_data_container:/data/db
      healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
        interval: 10s
        timeout: 10s
        retries: 3
volumes:
  mongodb_data_container:
