version: "3.3"
services:
    food-nginx:
      image: nginx:latest
      networks:
        - nginx-net
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./conf/:/etc/nginx/conf.d/:ro        
        - /etc/letsencrypt:/etc/letsencrypt

networks:
  nginx-net:
    external: true     