version: "3.3"
services:
    food-nginx:
      image: nginx:latest
      container_name: nginx
      restart: always
      networks:
        - nginx-net
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./conf/:/etc/nginx/conf.d/:ro        
        - ./certbot/conf/:/etc/nginx/ssl/:ro
        - /var/www/html/images:/usr/share/nginx/html/images
networks:
  nginx-net:
    external: true        
