version: "3.3"
services:
    food-nginx:
      image: nginx:latest
      container_name: nginx
      restart: always
      networks:
        - nginx-net
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./conf/:/etc/nginx/conf.d/:ro        
        - ./certbot/www:/var/www/certbot/
        - ./certbot/conf/:/etc/letsencrypt/

    certbot:
      image: certbot/certbot:latest
      volumes:
        - ./certbot/www/:/var/www/certbot/
        - ./certbot/conf/:/etc/letsencrypt/
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot -d sputnik-it.rs -d www.sputnik-it.rs --email your-email@example.com --agree-tos; sleep 12h & wait $${!}; done;'"
networks:
  nginx-net:
    external: true     