version: "3.3"
services:
    rest-api:
      image: restapi:latest
      environment:
        - "spring.data.mongodb.uri=mongodb://root:test@rest_mongo-db/test?authSource=admin&authMechanism=SCRAM-SHA-1"
        - "rest.path=/api/v1"
      ports:
        - "9097:9097"
      stdin_open: true
      tty: true
      depends_on:
        - mongo-db
      networks:
        - nginx-net
    mongo-db:
      image: mongo:4.2.0
      container_name: food-mongo
      command: mongod --port 27055
      ports:
        - "27055:27055"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=test
        - MONGO_INITDB_DATABASE=test
      volumes:
        - mongodb_data_container:/data/db
      healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo localhost:27055/test --quiet
        interval: 10s
        timeout: 10s
        retries: 3
      networks:
        - nginx-net
volumes:
  mongodb_data_container:
networks:
  nginx-net:
    external: true