version: "3.3"
services:
    mongo-db-texas:
      image: mongo:4.2.0
      command: mongod --port 27056
      ports:
        - "27056:27056"
      environment:
        - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_user
        - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_pw
        - MONGO_INITDB_DATABASE=test
      secrets:
        - db_user
        - db_pw        
      volumes:
        - mongodb_data_container:/data/db
      healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo localhost:27056/test --quiet
        interval: 10s
        timeout: 10s
        retries: 3
      networks:
        - nginx-net
        
    rest-api-texas:
      image: texas-restapi:latest
      ports:
        - "8097:8097"
      stdin_open: true
      tty: true
      depends_on:
        - mongo-db
      networks:
        - nginx-net
      secrets:
        - db_user
        - db_pw
     
volumes:
  mongodb_data_container:
networks:
  nginx-net:
    external: true

secrets:
  db_user:
    external: true
  db_pw:
    external: true    