version: "3.3"
services:
    viber-bot-texas:      
      image: bot:latest
      ports:
        - "8943:8943"
      stdin_open: true
      tty: true
      networks:
        nginx-net:

      environment:
        - LANG=C.UTF-8

networks:
  nginx-net:
    external: true