version: "3.3"
services:
    viber-bot:      
      image: bot:latest
      ports:
        - "9943:9943"
      stdin_open: true
      tty: true
      networks:
        nginx-net:
          ipv4_address: 10.0.1.252

      environment:
        - LANG=C.UTF-8

networks:
  nginx-net:
    external: true