version: "3.3"
services:
    food-bot:
      container_name: bot
      image: bot:latest
      restart: on-failure
      ports:
        - "9943:9943"
      stdin_open: true
      tty: true
      networks:
        - nginx-net
      environment:
        - LANG=C.UTF-8

networks:
  nginx-net:
    external: true