version: "3.3"
services:
    food-bot:
      image: bot.jar:latest
      restart: on-failure
      ports:
        - "9943:9943"
      stdin_open: true
      tty: true
      networks:
        - nginx-net

networks:
  nginx-net:
    external: true